export const getPokemonColour = {
  normal: '#DDCBD0',
  fighting: '#FCC1B0',
  flying: '#B2D2E8',
  poison: '#CFB7ED',
  ground: '#F4D1A6',
  rock: '#C5AEA8',
  bug: '#C1E0C8',
  ghost: '#D7C2D7',
  steel: '#C2D4CE',
  fire: '#EDC2C4',
  water: '#CBD5ED',
  grass: '#C0D4C8',
  electric: '#E2E2A0',
  psychic: '#DDCOCF',
  ice: '#C7D7DF',
  dragon: '#CADCDF',
  dark: '#C6C5E3',
  fairy: '#E4C0CF',
  unknown: '#CODFDD',
  shadow: '#CACACA',
};
