const HomeActionTypes = {
  GET_POKEMONS: 'GET_POKEMONS',
  GET_POKEMON_DETAIL: 'GET_POKEMON_DETAIL',
  GET_ALL_POKEMONS: 'GET_ALL_POKEMONS',
  GET_POKEMON_TYPE: 'GET_POKEMON_TYPE',
  GET_POKEMON_STAT: 'GET_POKEMON_STAT',
  GET_POKEMON_GENDER: 'GET_POKEMON_GENDER',
};

export default HomeActionTypes;
